### ISSUE TITLE
Paper Freer10a is not found on github site

### ISSUE THREAD

**Issue by wjmaddox** [mlresearch/v9#2]
Link to the pdf on the PMLR site comes up as 404: http://proceedings.mlr.press/v9/freer10a/freer10a.pdf

It is available on the github site at: https://github.com/mlresearch/v9/blob/gh-pages/freer10a/freer-roy10a.pdf

**Comment by lawrennd** [comment]
Thanks for reporting, I've renamed the file to fix this, should be working now!
